/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.14.3/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application

    id("com.diffplug.spotless") version "7.1.0"
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()

    maven("https://repo.opencollab.dev/main/") {
        name = "opencollab"
    }
}

dependencies {
    // Use JUnit Jupiter for testing.
    testImplementation(libs.junit.jupiter)

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    // This dependency is used by the application.
    implementation(libs.guava)

    implementation("org.geysermc.mcprotocollib:protocol:1.21.4-SNAPSHOT")
    implementation("net.raphimc:MinecraftAuth:4.1.1")
    implementation("org.cloudburstmc:nbt:3.0.0.Final")
    implementation("org.json:json:20250517")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    // Define the main class for the application.
    mainClass = "me.mauldin.super_sorting_system.McAgent"
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}

spotless {
	java {
		importOrder()
		removeUnusedImports()
		googleJavaFormat()
	}
}
